// Decomposes a morphology card's canonical answer (e.g. "first aorist active
// indicative second person plural") into an ordered sequence of single-
// dimension multiple-choice steps for the step-by-step parsing drill.
//
// Dimension ordering, fixed:
//   verbs:    tense → voice → mood → person → number   (+ case/number/gender
//             tail for participles, no person)
//   nominals: case → number → gender
//
// Wrong picks reveal the correct dimension answer, then advance.

// Master pool of choices per dimension. The decomposer derives the correct
// answer from the card's parsed answer string and pulls distractors from the
// remaining pool entries for that dimension.
const DIM_POOLS = {
  aspect: ['continuous', 'undefined', 'continuous/undefined', 'completed'],
  tense:  ['present', 'future', 'imperfect', 'aorist', 'first aorist', 'second aorist', 'perfect', 'pluperfect'],
  voice:  ['active', 'middle', 'passive', 'middle/passive'],
  mood:   ['indicative', 'subjunctive', 'imperative', 'infinitive', 'participle'],
  person: ['first', 'second', 'third'],
  case:   ['nominative', 'accusative', 'genitive', 'dative', 'vocative'],
  number: ['singular', 'plural'],
  gender: ['masculine', 'feminine', 'neuter']
};

const DIM_LABEL = {
  aspect: 'Aspect',
  tense:  'Tense',
  voice:  'Voice',
  mood:   'Mood',
  person: 'Person',
  case:   'Case',
  number: 'Number',
  gender: 'Gender'
};

// Aspect is implicit in tense in Duff's pedagogy. Present and future are
// genuinely ambiguous between continuous (imperfective) and undefined
// (aoristic) — the form alone doesn't pick one (progressive vs gnomic for
// the present; context decides for the future), so the right parse is the
// composite 'continuous/undefined'. Imperfect commits to continuous,
// aorist to undefined, perfect/pluperfect to completed. Exactly one
// correct aspect per tense; picking just one half of the composite for
// present/future overcommits and is marked wrong.
const TENSE_TO_ASPECT = {
  'present':       'continuous/undefined',
  'imperfect':     'continuous',
  'future':        'continuous/undefined',
  'aorist':        'undefined',
  'first aorist':  'undefined',
  'second aorist': 'undefined',
  'perfect':       'completed',
  'pluperfect':    'completed'
};

export function aspectForTense(tense) {
  return TENSE_TO_ASPECT[tense] || '';
}

// When the student gets the aspect step wrong, returns a short clarifying
// note explaining the mistake. Especially important when the picked value
// visually overlaps the correct one (e.g. picking "continuous" when the
// correct is "continuous/undefined") — the strikethrough alone reads like
// a close miss rather than a real error, so an explicit note disambiguates.
// Returns '' when no special note is warranted (e.g. picking "continuous"
// for an aorist; the standard "continuous → undefined" line is clear).
export function aspectMistakeNote(tense, picked, correct) {
  if (!tense || !picked || picked === correct) return '';
  if (correct === 'continuous/undefined') {
    return `${tense} is aspectually ambiguous — pick continuous/undefined, not just ${picked}`;
  }
  if (picked === 'continuous/undefined') {
    return `${tense} isn't ambiguous — it commits to ${correct}`;
  }
  return '';
}

const DIM_DISPLAY_SUFFIX = {
  person: ' person'
};

function findToken(text, regex) {
  if (!text) return '';
  const match = String(text).match(regex);
  return match ? match[0].toLowerCase() : '';
}

// Parse a canonical answer like "aorist active indicative first person plural"
// or "nominative singular masculine" into { tense, voice, mood, person, case,
// number, gender }, with missing dimensions left as ''.
//
// The parser accepts both the canonical long-form (auto-generated by
// paradigm_morphology.js — "first person plural", "masculine") and the
// abbreviated short-form used throughout hand-written grammar.js cards
// ("1st pl.", "masc."). Lookaheads on person prevent "1st aorist" /
// "2nd declension" from false-positiving as person markers.
const CASE_ABBREVS = { 'nom.': 'nominative', 'acc.': 'accusative', 'gen.': 'genitive', 'dat.': 'dative', 'voc.': 'vocative' };
const GENDER_ABBREVS = { 'masc.': 'masculine', 'fem.': 'feminine', 'neut.': 'neuter' };
const PERSON_WORDS = { '1st': 'first', '2nd': 'second', '3rd': 'third', first: 'first', second: 'second', third: 'third' };

function expandComposite(text, abbrevMap, canonicalList) {
  // Matches a slash-composite of either full canonical words ("nominative/
  // accusative") or matching short-forms ("nom./acc."). Returns the slash
  // composite in canonical form, or '' when nothing matches.
  const full = canonicalList.join('|');
  const fullRe = new RegExp(`\\b(${full})(?:\\/(?:${full}))*\\b`);
  const fullMatch = text.match(fullRe);
  if (fullMatch) return fullMatch[0];
  const shortKeys = Object.keys(abbrevMap).map(k => k.replace(/\./g, '\\.'));
  const short = shortKeys.join('|');
  const shortRe = new RegExp(`(${short})(?:\\/(?:${short}))*`);
  const shortMatch = text.match(shortRe);
  if (!shortMatch) return '';
  return shortMatch[0]
    .split('/')
    .map(piece => abbrevMap[piece] || piece)
    .join('/');
}

export function parseAnswerDimensions(answer) {
  const a = String(answer || '').toLowerCase();
  const cleaned = a.replace(/[(),;]/g, ' ').replace(/\s+/g, ' ').trim();

  const qualifierTense = findToken(cleaned, /\b(first aorist|second aorist)\b/);
  const tense = qualifierTense
    || findToken(cleaned, /\b(present|future|imperfect|aorist|perfect|pluperfect)\b/);
  const voice = findToken(cleaned, /\b(middle\/passive|middle or passive|active|middle|passive)\b/)
    .replace(/middle or passive/, 'middle/passive');
  const mood = findToken(cleaned, /\b(indicative|subjunctive|imperative|infinitive|participle)\b/);
  let person = findToken(cleaned, /\b(first|second|third) person\b/).replace(/\s+person$/, '');
  if (!person) {
    const abbrev = cleaned.match(/\b(1st|2nd|3rd|first|second|third)\b(?=\s+(?:sg\.?|pl\.?|singular|plural)\b)/);
    if (abbrev) person = PERSON_WORDS[abbrev[1]] || '';
  }
  const number = findToken(cleaned, /\b(singular|plural)\b/)
    || (/\bsg\.?\b/.test(cleaned) ? 'singular' : /\bpl\.?\b/.test(cleaned) ? 'plural' : '');

  // Case can be syncretic ("nominative/accusative" or "nom./acc.").
  const grammaticalCase = expandComposite(cleaned, CASE_ABBREVS, ['nominative', 'accusative', 'genitive', 'dative', 'vocative']);

  // Gender can be combined ("all genders" / "masculine/feminine/neuter" /
  // "masc./neut."). Canonicalize tri-gender to the splittable composite so
  // dimsCompatible can match it against a specific gender pick.
  const allGenders = /\ball genders?\b/.test(cleaned) || /\bmasculine\/feminine\/neuter\b/.test(cleaned) || /masc\.\/fem\.\/neut\./.test(cleaned);
  const gender = allGenders
    ? 'masculine/feminine/neuter'
    : expandComposite(cleaned, GENDER_ABBREVS, ['masculine', 'feminine', 'neuter']);

  // Aspect is derived from tense (Duff's pedagogy: aspect is the primary
  // category, with tense as a secondary marker). Missing tense → no aspect.
  const aspect = tense ? aspectForTense(tense) : '';

  return { aspect, tense, voice, mood, person, case: grammaticalCase, number, gender };
}

// Stable canonical ordering for parsing-mode MC option lists. Items present
// in DIM_POOLS keep that pedagogical order (present → future → imperfect →
// aorist → …; nom → acc → gen → dat → voc; etc.); composite/syncretic
// values not in DIM_POOLS (e.g. 'masculine/feminine/neuter') sort last,
// alphabetically among themselves. Used instead of random shuffling so the
// same dimension always presents its choices in the same order card-to-card
// — random reordering forced re-reading on every step and broke the
// muscle-memory mapping between paradigm-table position and option slot.
function sortChoicesCanonically(dimensionKey, values) {
  const canonical = DIM_POOLS[dimensionKey] || [];
  const ord = (v) => {
    const i = canonical.indexOf(v);
    return i === -1 ? canonical.length : i;
  };
  return [...values].sort((a, b) => {
    const oa = ord(a);
    const ob = ord(b);
    if (oa !== ob) return oa - ob;
    return String(a).localeCompare(String(b));
  });
}

// True iff the given dim value should be visible / included given the
// user's per-value filter map. Composite values (e.g. 'continuous/undefined',
// 'middle/passive') pass when at least one slash-component is enabled;
// aorist qualifiers ('first aorist' / 'second aorist') normalize to 'aorist'
// for the lookup. A missing filter map (or missing dim entry) is treated as
// "everything enabled" so the existing default-on behavior survives.
export function dimValuePassesFilter(dimensionKey, value, dimValueFilters) {
  if (!value || !dimValueFilters || typeof dimValueFilters !== 'object') return true;
  const sub = dimValueFilters[dimensionKey];
  if (!sub || typeof sub !== 'object') return true;
  const normalized = String(value).replace(/^(first |second )/, '');
  const parts = normalized.split('/');
  return parts.some((p) => sub[p] !== false);
}

function buildChoices(dimensionKey, correct, accessiblePool, dimValueFilters) {
  // Prefer the chapter-gated accessible pool when provided (only values that
  // appear in morph cards the student has access to at their current point in
  // the course). Fall back to the full DIM_POOLS list if no pool was passed —
  // useful for unit tests and for callers that don't gate.
  //
  // The full accessible pool is shown — every distinct value the student has
  // learned for this dimension to date — rather than a 4-choice cap. As the
  // course progresses the choice list grows, mirroring expanding paradigm
  // recognition.
  //
  // Per-value filters prune distractors the user has opted out of — but the
  // `correct` value is always kept regardless, so a step never becomes
  // unanswerable just because the user disabled that value as a distractor.
  const sourcePool = accessiblePool && accessiblePool.length
    ? accessiblePool
    : (DIM_POOLS[dimensionKey] || []);
  const seen = new Set([correct]);
  const all = [correct];
  for (const candidate of sourcePool) {
    if (seen.has(candidate)) continue;
    if (!dimValuePassesFilter(dimensionKey, candidate, dimValueFilters)) continue;
    seen.add(candidate);
    all.push(candidate);
  }
  return sortChoicesCanonically(dimensionKey, all);
}

// Walks a set of morph cards (e.g. every card whose source chapter is ≤ the
// student's max selected chapter) and returns the unique values that appear
// in each parsing dimension. Used to build chapter-gated MC distractor pools
// so the drill never asks about a tense/mood/case the textbook hasn't yet
// introduced. Person/number/voice/gender are conceptually foundational and
// have small fixed pools, so they're seeded with their full standard sets
// whenever a verb/nominal card is in scope — otherwise a card tagged with
// (say) voice=middle alone would render a single-choice voice step.
export function computeAccessibleDimensionPools(cards) {
  const pools = {
    aspect: new Set(), tense: new Set(), voice: new Set(), mood: new Set(), person: new Set(),
    case: new Set(), number: new Set(), gender: new Set()
  };
  let sawVerb = false;
  let sawNominal = false;
  (cards || []).forEach((card) => {
    if (!card || !(card.parsedAnswer || card.answer)) return;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
    Object.keys(pools).forEach((k) => {
      if (dims[k]) pools[k].add(dims[k]);
    });
    if (dims.tense || dims.voice || dims.person) sawVerb = true;
    if (dims.case || dims.gender) sawNominal = true;
    // Aspect pool: continuous, undefined, and the composite continuous/undefined
    // are foundational from the present onward, so always expose all three
    // as choices — the student needs to distinguish "either reading is valid"
    // from "this form commits to one reading" on every card. The composite is
    // never auto-correct from being present in the choices: it's only right
    // for present/future. 'completed' arrives via the per-card add above
    // when a perfect-stem form is in the accessible set.
    if (dims.tense) {
      pools.aspect.add('continuous');
      pools.aspect.add('undefined');
      pools.aspect.add('continuous/undefined');
    }
  });
  if (sawVerb) {
    ['first', 'second', 'third'].forEach(p => pools.person.add(p));
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    // Voice is intentionally NOT seeded as a whole — it stays whatever
    // the accessible cards have tagged. Duff doesn't introduce voice
    // formally until ch 15 (with deponent verbs covered ch 8/9 as the
    // bridge), so seeding all four voices would show "active vs
    // middle/passive" choices to chapter 5 students who only have
    // active forms in scope. Letting the pool grow organically means
    // chapters that haven't yet introduced voice see no voice
    // distractors; buildMorphSteps additionally skips the voice step
    // entirely for active-tagged cards before ch 15.
    //
    // BUT: once any non-active voice has shown up (chapter 8/9 onward
    // with deponents), seed 'active' as the comparison voice so the
    // deponent's middle/passive voice step doesn't render as a
    // single-choice no-info pick.
    const sawNonActiveVoice = [...pools.voice].some(v => v && v !== 'active');
    if (sawNonActiveVoice) pools.voice.add('active');
  }
  if (sawNominal) {
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    ['masculine', 'feminine', 'neuter'].forEach(g => pools.gender.add(g));
  }
  const out = {};
  Object.keys(pools).forEach((k) => { out[k] = [...pools[k]]; });
  return out;
}

function applyDisplaySuffix(dimensionKey, value) {
  const suffix = DIM_DISPLAY_SUFFIX[dimensionKey];
  return suffix ? `${value}${suffix}` : value;
}

// 2nd-person plural present (any voice) is genuinely syncretic in Koine
// Greek: the indicative and imperative are spelt the same — λύετε is both
// "you (pl.) are untying" and "untie!"; likewise λύεσθε for the middle/
// passive. The form alone doesn't pick one mood; only context (presence
// of a subject, surrounding clauses) decides. When a card's parse names
// this configuration we accept either mood at the Mood step, instead of
// marking the alternate reading wrong.
//
// Detected from the raw answer text so this works across canonical
// ("second person plural") and abbreviated ("2nd pl.") formats. Imperative
// cards may omit person entirely (structurally 2nd) — treated as 2nd-pl
// when the only number marker is plural and no 1st/3rd person tag appears.
export function isSecondPluralPresentMoodAmbiguity(answer, parsedDims) {
  if (!answer) return false;
  const dims = parsedDims || parseAnswerDimensions(answer);
  if (dims.tense !== 'present') return false;
  if (dims.mood !== 'indicative' && dims.mood !== 'imperative') return false;
  const a = String(answer).toLowerCase();
  const isPlural = dims.number === 'plural' || /\bplural\b/.test(a) || /\bpl\./.test(a);
  if (!isPlural) return false;
  if (dims.person === 'second') return true;
  if (/\b2nd\b/.test(a) || /\bsecond person\b/.test(a)) return true;
  // Imperative cards are structurally 2nd person and often omit person
  // markers entirely. Treat as 2nd plural when no other person is named.
  if (dims.mood === 'imperative' && !dims.person
      && !/\b(1st|3rd|first person|third person)\b/.test(a)) {
    return true;
  }
  return false;
}

// When the student picks a mood that requires more dimensions than the
// source card's parse class supplied, returns the dim keys to inject as
// ungraded follow-up steps. Example: card λῦε is a 2-singular imperative
// — its steps don't include person (the canonicalized answer drops "2nd"
// without "person"). If the student picks mood=indicative, they need to
// commit to a person before we can resolve their picks to a single Greek
// form; inject person (and number if the card also lacks one).
//
// Imperative is treated specially: it's structurally 2nd person (Koine has
// no 1st-person imperatives), so person is never injected — only number.
//
// Returns [] when no injection is needed. Voice is never injected here —
// it's introduced in chapter 15 and gated separately.
const FINITE_MOODS_NEEDING_PERSON_NUMBER = new Set(['indicative', 'subjunctive', 'optative']);
export function inferredFollowupDims(stepKey, picked, existingStepKeys) {
  if (stepKey !== 'mood' || !picked) return [];
  const have = existingStepKeys instanceof Set ? existingStepKeys : new Set(existingStepKeys || []);
  const out = [];
  if (FINITE_MOODS_NEEDING_PERSON_NUMBER.has(picked)) {
    if (!have.has('person')) out.push('person');
    if (!have.has('number')) out.push('number');
  } else if (picked === 'imperative') {
    // Structurally 2nd person — only number disambiguates the form.
    if (!have.has('number')) out.push('number');
  } else if (picked === 'participle') {
    if (!have.has('case'))   out.push('case');
    if (!have.has('number')) out.push('number');
    if (!have.has('gender')) out.push('gender');
  }
  // infinitive: no follow-ups needed (no person/number/case/gender).
  return out;
}

// Structural impossibilities in Koine Greek that don't depend on a specific
// lemma — these are paradigm-level gaps any verb shares. Separate from the
// per-lemma negative inventory in js/data/lemma_inventory.js (which handles
// lemma-specific gaps like aorist εἰμί). When the student's picks combine
// into one of these, the form lookup should explain *why* no morph exists
// instead of just rendering "[no morph exists]".
const STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES = [
  { tense: 'future',     mood: 'imperative',  why: 'no future imperative exists' },
  { tense: 'future',     mood: 'subjunctive', why: 'no future subjunctive exists' },
  { tense: 'imperfect',  mood: 'subjunctive', why: 'no imperfect subjunctive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'imperative',  why: 'no imperfect imperative exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'infinitive',  why: 'no imperfect infinitive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'participle',  why: 'no imperfect participle exists (imperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'subjunctive', why: 'no pluperfect subjunctive exists (pluperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'imperative',  why: 'no pluperfect imperative exists (pluperfect is indicative-only)' },
  // The perfect infinitive (λελυκέναι) and perfect participle (λελυκώς) do
  // double duty for both perfect and pluperfect aspect — Koine has no
  // distinct pluperfect non-indicative forms.
  { tense: 'pluperfect', mood: 'infinitive',  why: 'no pluperfect infinitive exists (the perfect infinitive covers both)' },
  { tense: 'pluperfect', mood: 'participle',  why: 'no pluperfect participle exists (the perfect participle covers both)' }
];

// Returns a short explanation when the picked (tense, mood) combo is
// structurally impossible in Koine, or null otherwise. Aorist qualifiers
// (first/second) are collapsed onto 'aorist' since they don't introduce
// new mood gaps.
export function structuralImpossibilityReason(pickedDims) {
  if (!pickedDims) return null;
  const tenseRaw = String(pickedDims.tense || '').toLowerCase();
  const mood = String(pickedDims.mood || '').toLowerCase();
  if (!tenseRaw || !mood) return null;
  const tense = tenseRaw.replace(/^(first |second )/, '');
  for (const entry of STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES) {
    if (entry.tense === tense && entry.mood === mood) return entry.why;
  }
  return null;
}

// Builds an ungraded follow-up step for the given dimension. Choices come
// from the chapter-gated accessible pool when available; falls back to
// the full DIM_POOLS. The returned step has `inferred: true` and no
// `correct` value — it's scored as informational, not graded against the
// source card.
export function buildInferredStep(dimKey, accessiblePools) {
  const pool = (accessiblePools && Array.isArray(accessiblePools[dimKey]) && accessiblePools[dimKey].length)
    ? accessiblePools[dimKey]
    : (DIM_POOLS[dimKey] || []);
  if (!pool.length) return null;
  const choices = sortChoicesCanonically(dimKey, pool);
  const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
  return {
    key: dimKey,
    label: DIM_LABEL[dimKey] || dimKey,
    correct: null,
    acceptable: [],
    choices,
    displayCorrect: '',
    displayChoices,
    inferred: true
  };
}

// Chapter at which Duff formally introduces voice contrasts (the
// active vs middle/passive distinction). Before this chapter the voice
// step is suppressed for active-tagged cards, since the only voice
// in scope is active and the step would be a no-info "pick active".
// Non-active voice (the deponent middle/passive of ἔρχομαι etc.,
// introduced ch 8/9) keeps the voice step regardless — the whole
// point of teaching deponents is the middle/passive form/active meaning
// contrast, so naming voice on those cards is on-curriculum even
// before ch 15.
const VOICE_INTRODUCED_AT_CHAPTER = 15;

// Returns ordered dimension steps for this card. Each step:
//   { key, label, correct, choices, displayChoices, displayCorrect }
// `accessiblePools` is the optional chapter-gated distractor pool produced by
// computeAccessibleDimensionPools — pass it in to restrict MC choices to
// values the textbook has introduced so far.
// `options.includeAspect` (default true) controls whether the walk asks the
// Aspect step. Aspect is derivable from tense, so users who don't want to
// drill the composite-vs-single distinction (continuous/undefined vs
// continuous) can turn it off.
// `options.maxChapter` is the student's max effective chapter (from
// deriveSelectionLevels). Used to gate the voice step.
export function buildMorphSteps(card, accessiblePools = null, options = {}) {
  if (!card || card.kind !== 'morph') return [];
  // Prefer the canonical parsed form when set — grammar.js cards can ship
  // a sparse human-friendly `answer` ("1st singular ('I am')") alongside
  // a `parsed:` ("present active indicative first person singular") that
  // populates every dimension the form actually carries.
  const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
  const includeAspect = options.includeAspect !== false;

  // Chapter-gated mood default. When the card is a finite verb (tense +
  // person/number, no case/gender) with no explicit mood in its parse,
  // AND the student's accessible pool already contains a non-indicative
  // mood (i.e. the curriculum has introduced something else to contrast
  // against), inject mood='indicative' so the Mood step appears and the
  // student commits explicitly rather than having indicative silently
  // implied. Before the contrast exists (early chapters), the Mood step
  // would be a no-info "pick indicative" — skipped.
  if (!dims.mood && (dims.tense || dims.voice) && (dims.person || dims.number)
      && !dims.case && !dims.gender) {
    const accessibleMoods = (accessiblePools && Array.isArray(accessiblePools.mood)) ? accessiblePools.mood : [];
    const hasContrast = accessibleMoods.some(m => m && m !== 'indicative');
    if (hasContrast) dims.mood = 'indicative';
  }

  // Determine the dimension order. Verbs lead with aspect → tense (Duff's
  // aspect-first pedagogy), then voice → mood → person → number, with a
  // case/number/gender tail for participles. Nominals skip the verb steps.
  const isVerb = !!(dims.tense || dims.voice || dims.person);
  const verbOrder = ['aspect', 'tense', 'voice', 'mood', 'person', 'case', 'number', 'gender'];
  const nominalOrder = ['case', 'number', 'gender', 'aspect', 'tense', 'voice', 'mood', 'person'];
  const order = (isVerb ? verbOrder : nominalOrder).filter(k => includeAspect || k !== 'aspect');

  const steps = [];
  const skippedCorrect = {}; // dim → correct value for steps we silently skipped
  const impliedDims = {};    // dim → correct value for steps skipped but kept in parse summary
  const maxChapter = Number.isFinite(options.maxChapter) ? options.maxChapter : Infinity;
  const dimToggles = (options.dimToggles && typeof options.dimToggles === 'object') ? options.dimToggles : null;
  const dimValueFilters = (options.dimValueFilters && typeof options.dimValueFilters === 'object') ? options.dimValueFilters : null;
  const multiGenderLemmas = options.multiGenderLemmas instanceof Set ? options.multiGenderLemmas : null;
  // Single-gender lemmas whose gender is non-obvious from the form
  // ending (1st-decl. masc. -ης/-ας nouns: προφήτης, μαθητής, …) —
  // override the single-gender auto-skip below so the gender step IS
  // asked. The form looks feminine; recalling the lemma is masculine is
  // the whole point of the drill for these.
  const mixedFormNouns = options.mixedFormNouns instanceof Set ? options.mixedFormNouns : null;
  for (const dimKey of order) {
    const correct = dims[dimKey];
    if (!correct) continue;
    // Imperative is structurally 2nd person in Koine — skip the person step
    // for imperative cards so the dimension count matches non-explicit
    // imperatives (e.g. "active imperative singular" with no "second person"
    // tag).
    if (dimKey === 'person' && dims.mood === 'imperative') continue;
    // Voice step: gate on chapter regardless of card voice. Duff
    // doesn't ask the student to choose a voice until ch 15, and the
    // deponent forms covered at ch 8/9 are taught as functionally
    // active (middle/passive in form, active in meaning) — so asking
    // "what voice is ἔρχομαι?" at ch 9 is a question Duff doesn't
    // expect a single right answer to. The voice gets silently filled
    // in (skippedCorrect) so the form lookup still resolves; at ch 15+
    // the step appears, with the deponent-accepts-active rule applied
    // when the step is built below.
    if (dimKey === 'voice' && maxChapter < VOICE_INTRODUCED_AT_CHAPTER) {
      skippedCorrect[dimKey] = correct;
      continue;
    }
    // Per-dim toggle: user-controlled opt-out. Off → step skipped, dim
    // doesn't contribute to stats, omitted from the parse summary; the
    // form lookup auto-fills the canonical correct value via
    // skippedCorrect below.
    if (dimToggles && dimKey !== 'aspect' && dimToggles[dimKey] === false) {
      skippedCorrect[dimKey] = correct;
      continue;
    }
    // Single-gender lemma auto-skip. Asking "what gender?" for a noun
    // like λόγος tests whether the student remembers the lemma's fixed
    // gender, not whether they're parsing the form — the form λόγου is
    // masculine because λόγος is, not because the genitive ending
    // distinguishes a gender. Multi-gender paradigms (articles,
    // adjectives, pronouns, participles) keep the step: there the form
    // genuinely commits to a gender. The implied gender is auto-filled
    // for form lookup AND surfaced in the final parse summary so the
    // canonical label still reads e.g. "genitive singular masculine".
    //
    // Exception: mixed-form nouns (1st-decl. masc. -ης/-ας like
    // προφήτης, μαθητής) keep the step. Their endings match the 1st-
    // decl. feminine pattern, so the form-shape misleads the student
    // into a feminine reading; the gender check is the whole point of
    // drilling these and the lemma's gender isn't "obvious from the
    // article" the way it is for λόγος.
    const isMixedFormNoun = !!(mixedFormNouns && card.lemma && mixedFormNouns.has(card.lemma));
    if (dimKey === 'gender' && multiGenderLemmas && card.lemma
        && !multiGenderLemmas.has(card.lemma)
        && !isMixedFormNoun) {
      skippedCorrect[dimKey] = correct;
      impliedDims[dimKey] = correct;
      continue;
    }
    const pool = accessiblePools ? accessiblePools[dimKey] : null;
    const choices = buildChoices(dimKey, correct, pool, dimValueFilters);
    const displayCorrect = applyDisplaySuffix(dimKey, correct);
    const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
    // Each dimension has exactly one correct value per card. For aspect on
    // present/future verbs the correct value is the composite
    // 'continuous/undefined' (since either reading is licensed by the form);
    // for imperfect/aorist/perfect/pluperfect it's a single specific aspect.
    // The aspect step carries a `context.tense` so the wrong-answer
    // comparator can spell out the mistake when picked and correct overlap
    // visually (e.g. picked "continuous" vs correct "continuous/undefined").
    const step = {
      key: dimKey,
      label: DIM_LABEL[dimKey] || dimKey,
      correct,
      acceptable: [correct],
      choices,
      displayCorrect,
      displayChoices
    };
    if (dimKey === 'aspect' && dims.tense) {
      step.context = { tense: dims.tense };
    }
    // Deponent voice handling. Duff treats deponent verbs (lemmas
    // ending in -μαι and εἰμί's future ἔσομαι family) as functionally
    // active even though the form is middle / middle-passive — so
    // when voice IS asked (ch 15+), both 'active' and the formal
    // middle voice should grade as correct. Genuine passives
    // (voice='passive') stay strict: passive isn't active in meaning.
    if (dimKey === 'voice' && (correct === 'middle' || correct === 'middle/passive')) {
      step.acceptable = [correct, 'active'];
    }
    if (dimKey === 'mood' && isSecondPluralPresentMoodAmbiguity(card.answer, dims)) {
      step.acceptable = ['indicative', 'imperative'];
    }
    steps.push(step);
  }
  // Attach the auto-filled-correct dim map as a property on the array
  // (rather than changing the return shape) so the caller can read it
  // alongside the steps for the form-lookup augmentation, while
  // callers that just want the step list keep working.
  steps.autoFilledDims = skippedCorrect;
  // `impliedDims` is a subset of skippedCorrect (currently just the
  // single-gender gender skip) that should still appear in the rendered
  // parse summary — the step wasn't asked, but the dim belongs to the
  // form's canonical label. Caller renders these inline with the
  // student-picked values.
  steps.impliedDims = impliedDims;
  return steps;
}

// ─── Per-lemma rolling stats (sliding window of last N attempts) ─────────
//
// Two parallel structures per lemma:
//   - `attempts`:  sliding window of last ATTEMPT_WINDOW raw attempts. Drives
//                  the "Last 20 attempts" header pct + per-dim chips.
//   - `inProgress` + `buckets`: disjoint 20-attempt rollups. Every time
//                  `totalAttempts` reaches a multiple of ATTEMPT_WINDOW,
//                  `inProgress` is snapshotted into `buckets` (capped at
//                  BUCKET_HISTORY) and reset. This is what the expandable
//                  bar chart visualizes — last 200 graded attempts in 10
//                  disjoint groups of 20.
//
// `stats.overall` mirrors the same shape but aggregates across every lemma.

const ATTEMPT_WINDOW = 20;
const BUCKET_HISTORY = 10;

export function ensureParadigmStepStats(store) {
  if (!store || typeof store !== 'object') return {};
  if (typeof store.byLemma !== 'object' || store.byLemma === null) store.byLemma = {};
  if (typeof store.overall !== 'object' || store.overall === null) {
    store.overall = { totalAttempts: 0, inProgress: { correct: 0, total: 0 }, buckets: [] };
  } else {
    if (!Number.isFinite(store.overall.totalAttempts)) store.overall.totalAttempts = 0;
    if (!store.overall.inProgress || typeof store.overall.inProgress !== 'object') {
      store.overall.inProgress = { correct: 0, total: 0 };
    }
    if (!Array.isArray(store.overall.buckets)) store.overall.buckets = [];
  }
  return store;
}

function ensureLemmaEntry(entry) {
  if (!Array.isArray(entry.attempts)) entry.attempts = [];
  if (!Number.isFinite(entry.totalAttempts)) entry.totalAttempts = 0;
  if (!entry.inProgress || typeof entry.inProgress !== 'object') entry.inProgress = { correct: 0, total: 0 };
  if (!Array.isArray(entry.buckets)) entry.buckets = [];
  return entry;
}

function accumulateDims(target, dimResults) {
  for (const v of Object.values(dimResults || {})) {
    target.total += 1;
    if (v) target.correct += 1;
  }
}

// Record one attempt: a fully walked card with per-dimension correctness.
// stats: { byLemma: { lemma: { attempts, totalAttempts, inProgress, buckets } },
//          overall: { totalAttempts, inProgress, buckets } }
export function recordParadigmAttempt(stats, lemma, dimResults) {
  if (!lemma || !dimResults) return;
  ensureParadigmStepStats(stats);
  if (!stats.byLemma[lemma]) stats.byLemma[lemma] = {};
  const entry = ensureLemmaEntry(stats.byLemma[lemma]);

  // 1) Sliding window of raw attempts (drives the header pct + per-dim chips).
  entry.attempts.push({ at: Date.now(), dims: { ...dimResults } });
  while (entry.attempts.length > ATTEMPT_WINDOW) entry.attempts.shift();

  // 2) Disjoint per-lemma bucket aggregation. Increment on every attempt
  //    regardless of dim count so 20 cards = one bucket.
  entry.totalAttempts += 1;
  accumulateDims(entry.inProgress, dimResults);
  if (entry.totalAttempts % ATTEMPT_WINDOW === 0) {
    entry.buckets.push({
      correct: entry.inProgress.correct,
      total: entry.inProgress.total,
      at: Date.now()
    });
    while (entry.buckets.length > BUCKET_HISTORY) entry.buckets.shift();
    entry.inProgress = { correct: 0, total: 0 };
  }

  // 3) Overall (cross-paradigm) bucket aggregation. Mirrors per-lemma logic.
  const overall = stats.overall;
  overall.totalAttempts += 1;
  accumulateDims(overall.inProgress, dimResults);
  if (overall.totalAttempts % ATTEMPT_WINDOW === 0) {
    overall.buckets.push({
      correct: overall.inProgress.correct,
      total: overall.inProgress.total,
      at: Date.now()
    });
    while (overall.buckets.length > BUCKET_HISTORY) overall.buckets.shift();
    overall.inProgress = { correct: 0, total: 0 };
  }
}

// Aggregate accuracy for a single lemma's recent attempts.
// Returns { total, correct, perDim: { tense: {seen, correct}, ... } }
export function summarizeLemmaStats(stats, lemma) {
  const empty = { total: 0, correct: 0, perDim: {}, attempts: 0 };
  if (!stats || !stats.byLemma || !stats.byLemma[lemma]) return empty;
  const attempts = stats.byLemma[lemma].attempts || [];
  let total = 0, correct = 0;
  const perDim = {};
  for (const a of attempts) {
    if (!a || !a.dims) continue;
    for (const [dim, val] of Object.entries(a.dims)) {
      if (!perDim[dim]) perDim[dim] = { seen: 0, correct: 0 };
      perDim[dim].seen += 1;
      if (val) perDim[dim].correct += 1;
      total += 1;
      if (val) correct += 1;
    }
  }
  return { total, correct, perDim, attempts: attempts.length };
}

export function getAllLemmaStats(stats) {
  if (!stats || !stats.byLemma) return [];
  return Object.keys(stats.byLemma).map((lemma) => ({
    lemma,
    ...summarizeLemmaStats(stats, lemma)
  })).filter((s) => s.attempts > 0);
}

export function getParadigmStepDimensionLabel(dimKey) {
  return DIM_LABEL[dimKey] || dimKey;
}

export function getParadigmStepAttemptWindow() {
  return ATTEMPT_WINDOW;
}

export function getParadigmBucketHistorySize() {
  return BUCKET_HISTORY;
}

// Buckets + in-progress for one lemma. The chart consumer reads both: each
// completed bucket renders as a solid bar, in-progress (if it has any
// recorded dims) renders as a muted trailing bar so the user can see their
// current bucket filling.
export function getLemmaBucketSeries(stats, lemma) {
  const entry = stats?.byLemma?.[lemma];
  if (!entry) return { buckets: [], inProgress: { correct: 0, total: 0 }, totalAttempts: 0 };
  return {
    buckets: Array.isArray(entry.buckets) ? entry.buckets : [],
    inProgress: entry.inProgress && typeof entry.inProgress === 'object'
      ? { correct: Number(entry.inProgress.correct) || 0, total: Number(entry.inProgress.total) || 0 }
      : { correct: 0, total: 0 },
    totalAttempts: Number(entry.totalAttempts) || 0
  };
}

// Same shape as getLemmaBucketSeries, but for the cross-paradigm aggregate.
export function getOverallBucketSeries(stats) {
  const overall = stats?.overall;
  if (!overall) return { buckets: [], inProgress: { correct: 0, total: 0 }, totalAttempts: 0 };
  return {
    buckets: Array.isArray(overall.buckets) ? overall.buckets : [],
    inProgress: overall.inProgress && typeof overall.inProgress === 'object'
      ? { correct: Number(overall.inProgress.correct) || 0, total: Number(overall.inProgress.total) || 0 }
      : { correct: 0, total: 0 },
    totalAttempts: Number(overall.totalAttempts) || 0
  };
}

// Cumulative across every lemma's sliding window. Used to render the "All
// paradigms" overall row header — a single dim-accuracy pct over whatever's
// currently in everyone's rolling-20 window. Independent of buckets so it
// stays meaningful even when the user hasn't completed a full bucket yet.
export function summarizeOverallRolling(stats) {
  const empty = { total: 0, correct: 0, perDim: {}, attempts: 0, paradigms: 0 };
  if (!stats?.byLemma) return empty;
  let total = 0, correct = 0, attempts = 0, paradigms = 0;
  const perDim = {};
  for (const lemma of Object.keys(stats.byLemma)) {
    const entry = stats.byLemma[lemma];
    const list = Array.isArray(entry?.attempts) ? entry.attempts : [];
    if (!list.length) continue;
    paradigms += 1;
    attempts += list.length;
    for (const a of list) {
      if (!a || !a.dims) continue;
      for (const [dim, val] of Object.entries(a.dims)) {
        if (!perDim[dim]) perDim[dim] = { seen: 0, correct: 0 };
        perDim[dim].seen += 1;
        total += 1;
        if (val) { perDim[dim].correct += 1; correct += 1; }
      }
    }
  }
  return { total, correct, perDim, attempts, paradigms };
}
