// Decomposes a morphology card's canonical answer (e.g. "first aorist active
// indicative second person plural") into an ordered sequence of single-
// dimension multiple-choice steps for the step-by-step parsing drill.
//
// Dimension ordering, fixed:
//   verbs:    tense → voice → mood → person → number   (+ case/number/gender
//             tail for participles, no person)
//   nominals: case → number → gender
//
// Wrong picks reveal the correct dimension answer, then advance.

// Master pool of choices per dimension. The decomposer derives the correct
// answer from the card's parsed answer string and pulls distractors from the
// remaining pool entries for that dimension.
const DIM_POOLS = {
  aspect: ['continuous', 'undefined', 'continuous/undefined', 'completed'],
  tense:  ['present', 'future', 'imperfect', 'aorist', 'first aorist', 'second aorist', 'perfect', 'pluperfect'],
  voice:  ['active', 'middle', 'passive', 'middle/passive'],
  mood:   ['indicative', 'subjunctive', 'imperative', 'infinitive', 'participle'],
  person: ['first', 'second', 'third'],
  case:   ['nominative', 'accusative', 'genitive', 'dative', 'vocative'],
  number: ['singular', 'plural'],
  gender: ['masculine', 'feminine', 'neuter']
};

const DIM_LABEL = {
  aspect: 'Aspect',
  tense:  'Tense',
  voice:  'Voice',
  mood:   'Mood',
  person: 'Person',
  case:   'Case',
  number: 'Number',
  gender: 'Gender'
};

// Aspect is implicit in tense in Duff's pedagogy. Present and future are
// genuinely ambiguous between continuous (imperfective) and undefined
// (aoristic) — the form alone doesn't pick one (progressive vs gnomic for
// the present; context decides for the future), so the right parse is the
// composite 'continuous/undefined'. Imperfect commits to continuous,
// aorist to undefined, perfect/pluperfect to completed. Exactly one
// correct aspect per tense; picking just one half of the composite for
// present/future overcommits and is marked wrong.
const TENSE_TO_ASPECT = {
  'present':       'continuous/undefined',
  'imperfect':     'continuous',
  'future':        'continuous/undefined',
  'aorist':        'undefined',
  'first aorist':  'undefined',
  'second aorist': 'undefined',
  'perfect':       'completed',
  'pluperfect':    'completed'
};

export function aspectForTense(tense) {
  return TENSE_TO_ASPECT[tense] || '';
}

// When the student gets the aspect step wrong, returns a short clarifying
// note explaining the mistake. Especially important when the picked value
// visually overlaps the correct one (e.g. picking "continuous" when the
// correct is "continuous/undefined") — the strikethrough alone reads like
// a close miss rather than a real error, so an explicit note disambiguates.
// Returns '' when no special note is warranted (e.g. picking "continuous"
// for an aorist; the standard "continuous → undefined" line is clear).
export function aspectMistakeNote(tense, picked, correct) {
  if (!tense || !picked || picked === correct) return '';
  if (correct === 'continuous/undefined') {
    return `${tense} is aspectually ambiguous — pick continuous/undefined, not just ${picked}`;
  }
  if (picked === 'continuous/undefined') {
    return `${tense} isn't ambiguous — it commits to ${correct}`;
  }
  return '';
}

const DIM_DISPLAY_SUFFIX = {
  person: ' person'
};

function findToken(text, regex) {
  if (!text) return '';
  const match = String(text).match(regex);
  return match ? match[0].toLowerCase() : '';
}

// Parse a canonical answer like "aorist active indicative first person plural"
// or "nominative singular masculine" into { tense, voice, mood, person, case,
// number, gender }, with missing dimensions left as ''.
//
// The parser accepts both the canonical long-form (auto-generated by
// paradigm_morphology.js — "first person plural", "masculine") and the
// abbreviated short-form used throughout hand-written grammar.js cards
// ("1st pl.", "masc."). Lookaheads on person prevent "1st aorist" /
// "2nd declension" from false-positiving as person markers.
const CASE_ABBREVS = { 'nom.': 'nominative', 'acc.': 'accusative', 'gen.': 'genitive', 'dat.': 'dative', 'voc.': 'vocative' };
const GENDER_ABBREVS = { 'masc.': 'masculine', 'fem.': 'feminine', 'neut.': 'neuter' };
const PERSON_WORDS = { '1st': 'first', '2nd': 'second', '3rd': 'third', first: 'first', second: 'second', third: 'third' };

function expandComposite(text, abbrevMap, canonicalList) {
  // Matches a slash-composite of either full canonical words ("nominative/
  // accusative") or matching short-forms ("nom./acc."). Returns the slash
  // composite in canonical form, or '' when nothing matches.
  const full = canonicalList.join('|');
  const fullRe = new RegExp(`\\b(${full})(?:\\/(?:${full}))*\\b`);
  const fullMatch = text.match(fullRe);
  if (fullMatch) return fullMatch[0];
  const shortKeys = Object.keys(abbrevMap).map(k => k.replace(/\./g, '\\.'));
  const short = shortKeys.join('|');
  const shortRe = new RegExp(`(${short})(?:\\/(?:${short}))*`);
  const shortMatch = text.match(shortRe);
  if (!shortMatch) return '';
  return shortMatch[0]
    .split('/')
    .map(piece => abbrevMap[piece] || piece)
    .join('/');
}

export function parseAnswerDimensions(answer) {
  const a = String(answer || '').toLowerCase();
  const cleaned = a.replace(/[(),;]/g, ' ').replace(/\s+/g, ' ').trim();

  const qualifierTense = findToken(cleaned, /\b(first aorist|second aorist)\b/);
  const tense = qualifierTense
    || findToken(cleaned, /\b(present|future|imperfect|aorist|perfect|pluperfect)\b/);
  const voice = findToken(cleaned, /\b(middle\/passive|middle or passive|active|middle|passive)\b/)
    .replace(/middle or passive/, 'middle/passive');
  const mood = findToken(cleaned, /\b(indicative|subjunctive|imperative|infinitive|participle)\b/);
  let person = findToken(cleaned, /\b(first|second|third) person\b/).replace(/\s+person$/, '');
  if (!person) {
    const abbrev = cleaned.match(/\b(1st|2nd|3rd|first|second|third)\b(?=\s+(?:sg\.?|pl\.?|singular|plural)\b)/);
    if (abbrev) person = PERSON_WORDS[abbrev[1]] || '';
  }
  const number = findToken(cleaned, /\b(singular|plural)\b/)
    || (/\bsg\.?\b/.test(cleaned) ? 'singular' : /\bpl\.?\b/.test(cleaned) ? 'plural' : '');

  // Case can be syncretic ("nominative/accusative" or "nom./acc.").
  const grammaticalCase = expandComposite(cleaned, CASE_ABBREVS, ['nominative', 'accusative', 'genitive', 'dative', 'vocative']);

  // Gender can be combined ("all genders" / "masculine/feminine/neuter" /
  // "masc./neut."). Canonicalize tri-gender to the splittable composite so
  // dimsCompatible can match it against a specific gender pick.
  const allGenders = /\ball genders?\b/.test(cleaned) || /\bmasculine\/feminine\/neuter\b/.test(cleaned) || /masc\.\/fem\.\/neut\./.test(cleaned);
  const gender = allGenders
    ? 'masculine/feminine/neuter'
    : expandComposite(cleaned, GENDER_ABBREVS, ['masculine', 'feminine', 'neuter']);

  // Aspect is derived from tense (Duff's pedagogy: aspect is the primary
  // category, with tense as a secondary marker). Missing tense → no aspect.
  const aspect = tense ? aspectForTense(tense) : '';

  return { aspect, tense, voice, mood, person, case: grammaticalCase, number, gender };
}

// Stable canonical ordering for parsing-mode MC option lists. Items present
// in DIM_POOLS keep that pedagogical order (present → future → imperfect →
// aorist → …; nom → acc → gen → dat → voc; etc.); composite/syncretic
// values not in DIM_POOLS (e.g. 'masculine/feminine/neuter') sort last,
// alphabetically among themselves. Used instead of random shuffling so the
// same dimension always presents its choices in the same order card-to-card
// — random reordering forced re-reading on every step and broke the
// muscle-memory mapping between paradigm-table position and option slot.
function sortChoicesCanonically(dimensionKey, values) {
  const canonical = DIM_POOLS[dimensionKey] || [];
  const ord = (v) => {
    const i = canonical.indexOf(v);
    return i === -1 ? canonical.length : i;
  };
  return [...values].sort((a, b) => {
    const oa = ord(a);
    const ob = ord(b);
    if (oa !== ob) return oa - ob;
    return String(a).localeCompare(String(b));
  });
}

// True iff the given dim value should be visible / included given the
// user's per-value filter map. Composite values (e.g. 'continuous/undefined',
// 'middle/passive') pass when at least one slash-component is enabled;
// aorist qualifiers ('first aorist' / 'second aorist') normalize to 'aorist'
// for the lookup. A missing filter map (or missing dim entry) is treated as
// "everything enabled" so the existing default-on behavior survives.
export function dimValuePassesFilter(dimensionKey, value, dimValueFilters) {
  if (!value || !dimValueFilters || typeof dimValueFilters !== 'object') return true;
  const sub = dimValueFilters[dimensionKey];
  if (!sub || typeof sub !== 'object') return true;
  const normalized = String(value).replace(/^(first |second )/, '');
  const parts = normalized.split('/');
  return parts.some((p) => sub[p] !== false);
}

function buildChoices(dimensionKey, correct, accessiblePool, dimValueFilters) {
  // Prefer the chapter-gated accessible pool when provided (only values that
  // appear in morph cards the student has access to at their current point in
  // the course). Fall back to the full DIM_POOLS list if no pool was passed —
  // useful for unit tests and for callers that don't gate.
  //
  // The full accessible pool is shown — every distinct value the student has
  // learned for this dimension to date — rather than a 4-choice cap. As the
  // course progresses the choice list grows, mirroring expanding paradigm
  // recognition.
  //
  // Per-value filters prune distractors the user has opted out of — but the
  // `correct` value is always kept regardless, so a step never becomes
  // unanswerable just because the user disabled that value as a distractor.
  const sourcePool = accessiblePool && accessiblePool.length
    ? accessiblePool
    : (DIM_POOLS[dimensionKey] || []);
  const seen = new Set([correct]);
  const all = [correct];
  for (const candidate of sourcePool) {
    if (seen.has(candidate)) continue;
    if (!dimValuePassesFilter(dimensionKey, candidate, dimValueFilters)) continue;
    seen.add(candidate);
    all.push(candidate);
  }
  return sortChoicesCanonically(dimensionKey, all);
}

// Walks a set of morph cards (e.g. every card whose source chapter is ≤ the
// student's max selected chapter) and returns the unique values that appear
// in each parsing dimension. Used to build chapter-gated MC distractor pools
// so the drill never asks about a tense/mood/case the textbook hasn't yet
// introduced. Person/number/voice/gender are conceptually foundational and
// have small fixed pools, so they're seeded with their full standard sets
// whenever a verb/nominal card is in scope — otherwise a card tagged with
// (say) voice=middle alone would render a single-choice voice step.
export function computeAccessibleDimensionPools(cards) {
  const pools = {
    aspect: new Set(), tense: new Set(), voice: new Set(), mood: new Set(), person: new Set(),
    case: new Set(), number: new Set(), gender: new Set()
  };
  let sawVerb = false;
  let sawNominal = false;
  (cards || []).forEach((card) => {
    if (!card || !(card.parsedAnswer || card.answer)) return;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
    Object.keys(pools).forEach((k) => {
      if (dims[k]) pools[k].add(dims[k]);
    });
    if (dims.tense || dims.voice || dims.person) sawVerb = true;
    if (dims.case || dims.gender) sawNominal = true;
    // Aspect pool: continuous, undefined, and the composite continuous/undefined
    // are foundational from the present onward, so always expose all three
    // as choices — the student needs to distinguish "either reading is valid"
    // from "this form commits to one reading" on every card. The composite is
    // never auto-correct from being present in the choices: it's only right
    // for present/future. 'completed' arrives via the per-card add above
    // when a perfect-stem form is in the accessible set.
    if (dims.tense) {
      pools.aspect.add('continuous');
      pools.aspect.add('undefined');
      pools.aspect.add('continuous/undefined');
    }
  });
  if (sawVerb) {
    ['first', 'second', 'third'].forEach(p => pools.person.add(p));
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    // Voice is intentionally NOT seeded as a whole — it stays whatever
    // the accessible cards have tagged. Duff doesn't introduce voice
    // formally until ch 15 (with deponent verbs covered ch 8/9 as the
    // bridge), so seeding all four voices would show "active vs
    // middle/passive" choices to chapter 5 students who only have
    // active forms in scope. Letting the pool grow organically means
    // chapters that haven't yet introduced voice see no voice
    // distractors; buildMorphSteps additionally skips the voice step
    // entirely for active-tagged cards before ch 15.
    //
    // BUT: once any non-active voice has shown up (chapter 8/9 onward
    // with deponents), seed 'active' as the comparison voice so the
    // deponent's middle/passive voice step doesn't render as a
    // single-choice no-info pick.
    const sawNonActiveVoice = [...pools.voice].some(v => v && v !== 'active');
    if (sawNonActiveVoice) pools.voice.add('active');
  }
  if (sawNominal) {
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    ['masculine', 'feminine', 'neuter'].forEach(g => pools.gender.add(g));
  }
  const out = {};
  Object.keys(pools).forEach((k) => { out[k] = [...pools[k]]; });
  return out;
}

function applyDisplaySuffix(dimensionKey, value) {
  const suffix = DIM_DISPLAY_SUFFIX[dimensionKey];
  return suffix ? `${value}${suffix}` : value;
}

// 2nd-person plural present (any voice) is genuinely syncretic in Koine
// Greek: the indicative and imperative are spelt the same — λύετε is both
// "you (pl.) are untying" and "untie!"; likewise λύεσθε for the middle/
// passive. The form alone doesn't pick one mood; only context (presence
// of a subject, surrounding clauses) decides. When a card's parse names
// this configuration we accept either mood at the Mood step, instead of
// marking the alternate reading wrong.
//
// Detected from the raw answer text so this works across canonical
// ("second person plural") and abbreviated ("2nd pl.") formats. Imperative
// cards may omit person entirely (structurally 2nd) — treated as 2nd-pl
// when the only number marker is plural and no 1st/3rd person tag appears.
export function isSecondPluralPresentMoodAmbiguity(answer, parsedDims) {
  if (!answer) return false;
  const dims = parsedDims || parseAnswerDimensions(answer);
  if (dims.tense !== 'present') return false;
  if (dims.mood !== 'indicative' && dims.mood !== 'imperative') return false;
  const a = String(answer).toLowerCase();
  const isPlural = dims.number === 'plural' || /\bplural\b/.test(a) || /\bpl\./.test(a);
  if (!isPlural) return false;
  if (dims.person === 'second') return true;
  if (/\b2nd\b/.test(a) || /\bsecond person\b/.test(a)) return true;
  // Imperative cards are structurally 2nd person and often omit person
  // markers entirely. Treat as 2nd plural when no other person is named.
  if (dims.mood === 'imperative' && !dims.person
      && !/\b(1st|3rd|first person|third person)\b/.test(a)) {
    return true;
  }
  return false;
}

// Short "how to tell it apart" hints for forms that are easy to confuse with a
// neighbouring parse. Triggered off the parsed dimensions (reliable) and worded
// to stay true across the regular ω-verb, contract, μι-, and deponent
// paradigms the drill covers — each hint names the exception where the simple
// rule breaks (liquid futures, 2nd-aorist passives) rather than overclaiming.
// Shown in the forward (Greek → English) walk summary, alongside the
// ambiguous-imperative note. Returns [] when nothing applies.
//
// Kept to patterns whose distinguishing marker is genuinely systematic:
// present↔future σ, the past-indicative augment (+ the imperfect ‑ον 1sg/3pl
// syncretism), the aorist-passive ‑θη‑, perfect/pluperfect reduplication, the
// participle suffix/declension tells, and the infinitive endings. (The aorist's
// ‑σα‑ is intentionally NOT hinted — κ-aorists ἔδωκα, 2nd aorists, and liquid
// aorists ἔμεινα all break it.)
export function confusableFormHints(answer, parsedDims, form) {
  const dims = parsedDims || parseAnswerDimensions(answer || '');
  if (!dims) return [];
  const { tense, voice, mood } = dims;
  const isMiddlePassive = voice === 'middle' || voice === 'passive' || voice === 'middle/passive';
  const formNfc = form ? String(form).normalize('NFC').trim() : '';
  const hints = [];
  // Present ↔ future: the tense-forming σ — the single most-confused contrast
  // in the regular paradigm (λύει vs λύσει). Holds for active and
  // middle/passive; the 2 pl. m/p is the cleanest tell (one σ vs two).
  if ((tense === 'present' || tense === 'future') && mood === 'indicative') {
    hints.push(isMiddlePassive
      ? 'Present vs future middle/passive: the future slots a σ before the ending — λύομαι → λύσομαι, and 2 pl. λύεσθε (one σ) → λύσεσθε (two σ). Liquid/nasal stems (μένω, κρίνω) hide the σ and contract instead: μενοῦμαι.'
      : 'Present vs future active: the future slots a σ between stem and ending — λύω → λύσω, λύει → λύσει. Liquid/nasal stems (μένω, κρίνω) hide the σ and contract instead: μενῶ.');
  }
  // Augment = a past-tense indicative. Imperfect, aorist, and pluperfect
  // indicatives all carry an augment; it appears ONLY in the indicative, so it
  // cleanly separates e.g. the aorist indicative ἔλυσα from the augmentless
  // aorist subjunctive λύσω / infinitive λῦσαι / participle λύσας, and the
  // imperfect from the present. (Perfect is excluded — it reduplicates instead
  // of augmenting.)
  const isPastIndicative = mood === 'indicative'
    && (tense === 'imperfect' || tense === 'aorist' || tense === 'first aorist'
        || tense === 'second aorist' || tense === 'pluperfect');
  if (isPastIndicative) {
    hints.push('Augment = a past-tense indicative: a prefixed ἐ‑/ἔ‑ (ἔλυον, ἔλυσα, ἐλύθην) or a lengthened initial vowel (ἀκούω → ἤκουον); in compounds it sits after the prefix (ἀπ‑έ‑θανον). It shows up only in the indicative — the same tense’s subjunctive, infinitive, and participle have no augment (λύσω, λῦσαι, λύσας).');
  }
  // Imperfect active ‑ον is identical in the 1 sg. and 3 pl. (ἔλυον). Flag it
  // only when the form actually shows that ending, so it never misfires on a
  // μι-verb (ἐδίδουν 1 sg. ≠ ἐδίδοσαν 3 pl.).
  if (tense === 'imperfect' && mood === 'indicative' && /ον$/.test(formNfc)) {
    hints.push('Imperfect active ‑ον is spelt the same in the 1 sg. and the 3 pl. (ἔλυον = “I was untying” or “they were untying”) — only context tells them apart.');
  }
  // Aorist passive: the ‑θη‑ infix.
  if (tense === 'aorist' && voice === 'passive') {
    hints.push('Aorist passive: the ‑θη‑ infix is the tell (ἐ‑λύ‑θη‑ν, ἐ‑λύ‑θη‑ς …). A few verbs take a bare ‑η‑ instead — the 2nd aorist passive, e.g. ἐ‑γράφ‑η‑ν.');
  }
  // Perfect / pluperfect: reduplication is the signature.
  if (tense === 'perfect' || tense === 'pluperfect') {
    hints.push('Perfect/pluperfect: the reduplication (usually the initial consonant + ε — λέ‑λυκα, λέ‑λυμαι) marks the stem, and the active usually adds a ‑κ‑ (λέλυκα). The pluperfect prefixes an augment on top (ἐ‑λελύκειν).');
  }
  // Participle: the suffix carries voice, and the declension pattern tells you
  // where case/gender live. ‑μενος is never active; the aorist passive (‑θείς)
  // is the one voice-marked participle that isn't ‑μενος.
  if (mood === 'participle') {
    hints.push('Participle voice is in the suffix: ‑μενος/‑μένη/‑μενον is middle or middle/passive (λυόμενος, λυσάμενος, λελυμένος) — never active. The aorist passive is the exception, ending ‑(θ)είς (λυθείς; a few verbs drop the θ — γραφείς). The active ‑ων/‑ας/‑ώς types and ‑θείς decline 3rd-declension in the masc./neut. and 1st-declension in the fem. (λύων, λύουσα, λῦον; gen. λύοντος, λυούσης), so case and gender show in the ending; ‑μενος types decline like a 2-1-2 adjective.');
  }
  // Infinitive endings: four shapes, three of them ending in ‑αι.
  if (mood === 'infinitive') {
    hints.push('Infinitives end in ‑ειν, ‑σαι, ‑ναι, or ‑σθαι — three of the four close in ‑αι. ‑σθαι is middle/passive (λύεσθαι); ‑ναι covers the aorist passive (λυθῆναι), perfect active (λελυκέναι), and μι-verbs/εἰμί (διδόναι, εἶναι); ‑σαι is the 1st-aorist active (λῦσαι); ‑ειν is the present/future and 2nd-aorist active (λύειν, εἰπεῖν).');
  }
  return hints;
}

// When the student picks a mood that requires more dimensions than the
// source card's parse class supplied, returns the dim keys to inject as
// ungraded follow-up steps. Example: card λῦε is a 2-singular imperative
// — its steps don't include person (the canonicalized answer drops "2nd"
// without "person"). If the student picks mood=indicative, they need to
// commit to a person before we can resolve their picks to a single Greek
// form; inject person (and number if the card also lacks one).
//
// Imperative is treated specially: it's structurally 2nd person (Koine has
// no 1st-person imperatives), so person is never injected — only number.
//
// Returns [] when no injection is needed. Voice is never injected here —
// it's introduced in chapter 15 and gated separately.
const FINITE_MOODS_NEEDING_PERSON_NUMBER = new Set(['indicative', 'subjunctive', 'optative']);
export function inferredFollowupDims(stepKey, picked, existingStepKeys) {
  if (stepKey !== 'mood' || !picked) return [];
  const have = existingStepKeys instanceof Set ? existingStepKeys : new Set(existingStepKeys || []);
  const out = [];
  if (FINITE_MOODS_NEEDING_PERSON_NUMBER.has(picked)) {
    if (!have.has('person')) out.push('person');
    if (!have.has('number')) out.push('number');
  } else if (picked === 'imperative') {
    // Structurally 2nd person — only number disambiguates the form.
    if (!have.has('number')) out.push('number');
  } else if (picked === 'participle') {
    if (!have.has('case'))   out.push('case');
    if (!have.has('number')) out.push('number');
    if (!have.has('gender')) out.push('gender');
  }
  // infinitive: no follow-ups needed (no person/number/case/gender).
  return out;
}

// Structural impossibilities in Koine Greek that don't depend on a specific
// lemma — these are paradigm-level gaps any verb shares. Separate from the
// per-lemma negative inventory in js/data/lemma_inventory.js (which handles
// lemma-specific gaps like aorist εἰμί). When the student's picks combine
// into one of these, the form lookup should explain *why* no morph exists
// instead of just rendering "[no morph exists]".
const STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES = [
  { tense: 'future',     mood: 'imperative',  why: 'no future imperative exists' },
  { tense: 'future',     mood: 'subjunctive', why: 'no future subjunctive exists' },
  { tense: 'imperfect',  mood: 'subjunctive', why: 'no imperfect subjunctive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'imperative',  why: 'no imperfect imperative exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'infinitive',  why: 'no imperfect infinitive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'participle',  why: 'no imperfect participle exists (imperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'subjunctive', why: 'no pluperfect subjunctive exists (pluperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'imperative',  why: 'no pluperfect imperative exists (pluperfect is indicative-only)' },
  // The perfect infinitive (λελυκέναι) and perfect participle (λελυκώς) do
  // double duty for both perfect and pluperfect aspect — Koine has no
  // distinct pluperfect non-indicative forms.
  { tense: 'pluperfect', mood: 'infinitive',  why: 'no pluperfect infinitive exists (the perfect infinitive covers both)' },
  { tense: 'pluperfect', mood: 'participle',  why: 'no pluperfect participle exists (the perfect participle covers both)' }
];

// Returns a short explanation when the picked (tense, mood) combo is
// structurally impossible in Koine, or null otherwise. Aorist qualifiers
// (first/second) are collapsed onto 'aorist' since they don't introduce
// new mood gaps.
export function structuralImpossibilityReason(pickedDims) {
  if (!pickedDims) return null;
  const tenseRaw = String(pickedDims.tense || '').toLowerCase();
  const mood = String(pickedDims.mood || '').toLowerCase();
  if (!tenseRaw || !mood) return null;
  const tense = tenseRaw.replace(/^(first |second )/, '');
  for (const entry of STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES) {
    if (entry.tense === tense && entry.mood === mood) return entry.why;
  }
  return null;
}

// ─── Paradigm-level value gaps ───────────────────────────────────────────
//
// Some paradigms own a dimension but carry only a subset of its values. The
// first/second personal pronouns (ἐγώ, σύ) inflect for person — but only
// first and second; the third-person personal pronoun is a separate paradigm
// (αὐτός, αὐτή, αὐτό). The person step still offers "third" as a distractor
// (any verb in scope seeds all three persons into the shared pool), so a
// student can pick a person the focused paradigm structurally lacks. When
// that happens there's no form to resolve and no point marching through the
// remaining dimensions — the walk should cut off and explain the gap, the
// same way structuralImpossibilityReason ends an impossible tense/mood walk.
//
// Scoped to `person` deliberately. Person is the one dimension where a
// paradigm legitimately owns the category yet lacks specific values without
// that being a chapter-gating artifact (chapter gating already prunes
// tense/mood/case distractors the textbook hasn't introduced). Nouns and
// adjectives have no person at all, so `presentValues.person` is empty for
// them and nothing is gated.
const PERSON_GLOSS = { first: 'first', second: 'second', third: 'third' };

// Curated structural gaps asserted from Greek morphology — NOT inferred from
// drilled data. Used only for gaps that present-values can't safely detect,
// because the missing value is also undrilled for paradigms that DO have it
// (e.g. most nouns never drill their vocative — λόγος has λόγε — so
// absence-in-data ≠ no-such-form). Keyed by focused-paradigm lemma → the dim
// values that genuinely don't exist for it. Kept to certain, lemma-stable
// gaps, same bar as lemma_inventory's impossible* lists.
//
// The Greek article and every pronoun inflect for the nominative, accusative,
// genitive, and dative only — they have NO vocative case. Nouns and adjectives
// DO have a vocative, so they are deliberately absent here and never gated.
const PARADIGM_STRUCTURAL_GAPS = {
  'ὁ, ἡ, τό':                           { case: ['vocative'] }, // the article
  'First and second personal pronouns': { case: ['vocative'] }, // ἐγώ / σύ
  'αὐτός, αὐτή, αὐτό':                  { case: ['vocative'] }, // intensive / 3rd-person
  'οὗτος, αὕτη, τοῦτο':                 { case: ['vocative'] }, // demonstrative "this"
  'ἐκεῖνος, ἐκείνη, ἐκεῖνο':            { case: ['vocative'] }, // demonstrative "that"
  'ὅς, ἥ, ὅ':                           { case: ['vocative'] }, // relative
  'τίς, τί':                            { case: ['vocative'] }  // interrogative / indefinite
};

// Set of values the focused paradigm actually carries per dimension, derived
// from its full (unfiltered) card pool. Composite values split so a paradigm
// tagged "first/second" registers both members. Consumed by paradigmGapReason.
export function computeParadigmPresentValues(cards) {
  const dimKeys = ['aspect', 'tense', 'voice', 'mood', 'person', 'case', 'number', 'gender'];
  const present = {};
  dimKeys.forEach((k) => { present[k] = new Set(); });
  (cards || []).forEach((card) => {
    if (!card) return;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer || '');
    dimKeys.forEach((k) => {
      if (!dims[k]) return;
      String(dims[k]).split('/').forEach((v) => { if (v) present[k].add(v); });
    });
  });
  return present;
}

// Returns { dim, picked, short, note } when the student's picks name a person
// the focused paradigm has no forms for, or null otherwise. `presentValues`
// comes from computeParadigmPresentValues over the paradigm's full pool. A
// paradigm with no person dimension (every noun/adjective) has an empty
// person set and is never gated; one that carries the picked person passes.
export function paradigmGapReason(pickedDims, presentValues, lemma) {
  if (!pickedDims || !presentValues) return null;
  // 1) Person on a person-bearing, tenseless paradigm (the 1st/2nd personal
  //    pronouns) that lacks the picked person — derived from drilled forms.
  const personGap = personGapReason(pickedDims, presentValues);
  if (personGap) return personGap;
  // 2) Curated structural gaps (currently case=vocative on the article and
  //    pronouns), asserted from morphology and guarded against the paradigm
  //    actually drilling the value.
  const curated = lemma ? PARADIGM_STRUCTURAL_GAPS[lemma] : null;
  if (curated) {
    const curatedGap = curatedGapReason(pickedDims, presentValues, curated);
    if (curatedGap) return curatedGap;
  }
  return null;
}

function personGapReason(pickedDims, presentValues) {
  const picked = pickedDims.person;
  const pool = presentValues.person;
  if (!picked || !pool || pool.size === 0) return null; // no person dim → nothing to gate
  // Only gate person for a person-bearing paradigm that is NOT a verb — i.e.
  // it has no tense in any of its forms. That's the 1st/2nd personal pronouns
  // (ἐγώ, σύ), which genuinely lack a third person. Verbs always conjugate all
  // three persons, so we never flag a person on them: a verb paradigm that
  // happened to drill only some persons must not look like it "lacks" one it
  // actually has. This keeps the gap bulletproof against undrilled verb forms.
  const tensePool = presentValues.tense;
  if (tensePool && tensePool.size > 0) return null;
  if (pool.has(picked)) return null;                     // picked person exists here → fine
  const pickedGloss = PERSON_GLOSS[picked] || picked;
  const have = ['first', 'second', 'third'].filter((p) => pool.has(p)).map((p) => PERSON_GLOSS[p] || p);
  const haveList = have.length <= 1 ? `${have[0] || ''} person` : `${have.join(' and ')} person`;
  let note = `This paradigm has no ${pickedGloss}-person forms — only ${haveList}.`;
  if (picked === 'third') {
    note += ' The third-person personal pronoun is a separate paradigm (αὐτός, αὐτή, αὐτό).';
  }
  return {
    dim: 'person',
    picked,
    short: `no ${pickedGloss}-person form in this paradigm`,
    note
  };
}

// The picked value for some dim is in the paradigm's declared-lacking list AND
// isn't actually drilled (the guard trusts data over a stale curated entry).
// Currently only case=vocative for the article + pronouns.
function curatedGapReason(pickedDims, presentValues, curated) {
  for (const dim of Object.keys(curated)) {
    const pickedVal = pickedDims[dim];
    const lacking = curated[dim];
    if (!pickedVal || !Array.isArray(lacking) || !lacking.includes(pickedVal)) continue;
    const dimPool = presentValues[dim];
    if (dimPool && dimPool.has(pickedVal)) continue; // paradigm actually drills it → trust data
    if (dim === 'case' && pickedVal === 'vocative') {
      return {
        dim,
        picked: pickedVal,
        short: 'no vocative in this paradigm',
        note: 'Pronouns and the article have no vocative case — they inflect for the nominative, accusative, genitive, and dative only.'
      };
    }
    return {
      dim,
      picked: pickedVal,
      short: `no ${pickedVal} ${dim} in this paradigm`,
      note: `This paradigm has no ${pickedVal} ${dim}.`
    };
  }
  return null;
}

// Pedagogical hints appended to a lemma's inventory-gap note, keyed by lemma.
// Kept tiny and explicit — only verbs with a genuinely suppletive / defective
// paradigm worth a one-line explanation.
const LEMMA_GAP_HINTS = {
  'εἰμί': 'εἰμί is suppletive — its aorist and perfect senses come from other verbs (e.g. ἐγενόμην, γέγονα).'
};

// Gap descriptor from a lemma's reviewed negative inventory
// (impossibleTenses / impossibleVoices / impossibleMoods in
// js/data/lemma_inventory.js): a tense/voice/mood the lemma genuinely lacks in
// Greek — e.g. the non-existent aorist of εἰμί. Returns { dim, picked, short,
// note } or null. Reads ONLY the hand-curated inventory; it never infers a gap
// from forms that merely aren't drilled, so it can't misfire on an incomplete
// paradigm. Mirrors render.js's isParseImpossibleForLemma, but produces the
// early-cutoff reason rather than the end-of-walk "[no morph exists]" verdict.
export function lemmaInventoryGapReason(pickedDims, inv, lemma) {
  if (!pickedDims || !inv) return null;
  const lemmaName = lemma || 'this verb';
  const checks = [
    ['tense', inv.impossibleTenses],
    ['voice', inv.impossibleVoices],
    ['mood',  inv.impossibleMoods]
  ];
  for (const [dim, list] of checks) {
    const picked = pickedDims[dim];
    if (!picked || !Array.isArray(list) || !list.length) continue;
    // A picked value can be syncretic ('middle/passive'); any component
    // landing in the impossible list disqualifies the combination.
    const parts = String(picked).split('/').filter(Boolean);
    const bad = parts.find((p) => list.includes(p));
    if (!bad) continue;
    const norm = bad.replace(/^(first |second )/, ''); // "first aorist" → "aorist"
    let note = `${lemmaName} has no ${norm} forms in Koine.`;
    const hint = LEMMA_GAP_HINTS[lemma];
    if (hint) note += ` ${hint}`;
    return {
      dim,
      picked: bad,
      short: `no ${norm} ${dim} for ${lemmaName}`,
      note
    };
  }
  return null;
}

// ─── Accent / breathing look-alike distractors ──────────────────────────
//
// Curated minimal pairs: a drilled paradigm form and another Greek word that
// is spelled identically except for accent or breathing. In the reverse drill
// (English → Greek, pick the form) the look-alike is a clean "did you read the
// accent?" distractor — the focused paradigm tells the student WHICH word they
// want, and they must pick the correctly-accented spelling. Toggle-optional,
// off by default. Hand-authored: auto-generating wrong-accent forms risks
// emitting a real-but-mislabeled word.
//
// Keyed by the tested form (NFC). Each twin carries the wrong-spelling form
// plus a one-line note naming the distinction. Bidirectional where both sides
// are drilled paradigms (article ↔ relative; intensive αὐτός ↔ demonstrative
// οὗτος).
const ACCENT_LOOKALIKES_RAW = {
  // Article (proclitic, unaccented) ↔ relative pronoun (accented) — accent only
  'ὁ':  [{ form: 'ὅ',  note: 'ὅ (accented) is the relative pronoun (neut.); ὁ is the masculine article.' }],
  'ὅ':  [{ form: 'ὁ',  note: 'ὁ (unaccented) is the masculine article; ὅ is the relative pronoun (neut.).' }],
  'ἡ':  [{ form: 'ἥ',  note: 'ἥ (accented) is the relative pronoun (fem.); ἡ is the feminine article.' }],
  'ἥ':  [{ form: 'ἡ',  note: 'ἡ (unaccented) is the feminine article; ἥ is the relative pronoun (fem.).' }],
  'οἱ': [{ form: 'οἵ', note: 'οἵ (accented) is the relative pronoun (masc. pl.); οἱ is the masculine article.' }],
  'οἵ': [{ form: 'οἱ', note: 'οἱ (unaccented) is the masculine article; οἵ is the relative pronoun (masc. pl.).' }],
  'αἱ': [{ form: 'αἵ', note: 'αἵ (accented) is the relative pronoun (fem. pl.); αἱ is the feminine article.' }],
  'αἵ': [{ form: 'αἱ', note: 'αἱ (unaccented) is the feminine article; αἵ is the relative pronoun (fem. pl.).' }],
  // Intensive αὐτός ↔ near demonstrative οὗτος — breathing (+ accent placement)
  'αὐτή': [{ form: 'αὕτη', note: 'αὕτη (rough breathing) is the demonstrative “this”; αὐτή (smooth) is αὐτός “she / herself”.' }],
  'αὕτη': [{ form: 'αὐτή', note: 'αὐτή (smooth breathing) is αὐτός “she / herself”; αὕτη (rough) is the demonstrative “this”.' }],
  // Interrogative (accented) ↔ indefinite (enclitic, unaccented) — accent only
  'τίς': [{ form: 'τις', note: 'τις (unaccented enclitic) is the indefinite “someone”; τίς (accented) is the interrogative “who?”.' }],
  'τί':  [{ form: 'τι',  note: 'τι (unaccented enclitic) is the indefinite “something”; τί (accented) is the interrogative “what? / why?”.' }],
  // εἰμί 2 sg. ↔ conjunction — accent only
  'εἶ':  [{ form: 'εἰ',  note: 'εἰ is the conjunction “if”; εἶ (circumflex) is εἰμί “you are”.' }]
};

// NFC-normalized index, built once, so lookups match regardless of the
// composed/decomposed form of the incoming card's Greek string.
const ACCENT_LOOKALIKES = (() => {
  const out = {};
  for (const [key, twins] of Object.entries(ACCENT_LOOKALIKES_RAW)) {
    out[key.normalize('NFC')] = twins.map((t) => ({ form: String(t.form).normalize('NFC'), note: t.note }));
  }
  return out;
})();

// Returns the curated accent/breathing look-alikes for a tested form
// ([{ form, note }, …]), or [] when none. NFC-normalizes the query.
export function accentLookalikesFor(form) {
  if (!form) return [];
  const key = String(form).trim().normalize('NFC');
  return ACCENT_LOOKALIKES[key] || [];
}

// Builds an ungraded follow-up step for the given dimension. Choices come
// from the chapter-gated accessible pool when available; falls back to
// the full DIM_POOLS. The returned step has `inferred: true` and no
// `correct` value — it's scored as informational, not graded against the
// source card.
export function buildInferredStep(dimKey, accessiblePools) {
  const pool = (accessiblePools && Array.isArray(accessiblePools[dimKey]) && accessiblePools[dimKey].length)
    ? accessiblePools[dimKey]
    : (DIM_POOLS[dimKey] || []);
  if (!pool.length) return null;
  const choices = sortChoicesCanonically(dimKey, pool);
  const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
  return {
    key: dimKey,
    label: DIM_LABEL[dimKey] || dimKey,
    correct: null,
    acceptable: [],
    choices,
    displayCorrect: '',
    displayChoices,
    inferred: true
  };
}

// Chapter at which Duff formally introduces voice contrasts (the
// active vs middle/passive distinction). Before this chapter the voice
// step is suppressed for active-tagged cards, since the only voice
// in scope is active and the step would be a no-info "pick active".
// Non-active voice (the deponent middle/passive of ἔρχομαι etc.,
// introduced ch 8/9) keeps the voice step regardless — the whole
// point of teaching deponents is the middle/passive form/active meaning
// contrast, so naming voice on those cards is on-curriculum even
// before ch 15.
const VOICE_INTRODUCED_AT_CHAPTER = 15;

// Returns ordered dimension steps for this card. Each step:
//   { key, label, correct, choices, displayChoices, displayCorrect }
// `accessiblePools` is the optional chapter-gated distractor pool produced by
// computeAccessibleDimensionPools — pass it in to restrict MC choices to
// values the textbook has introduced so far.
// `options.includeAspect` (default true) controls whether the walk asks the
// Aspect step. Aspect is derivable from tense, so users who don't want to
// drill the composite-vs-single distinction (continuous/undefined vs
// continuous) can turn it off.
// `options.maxChapter` is the student's max effective chapter (from
// deriveSelectionLevels). Used to gate the voice step.
export function buildMorphSteps(card, accessiblePools = null, options = {}) {
  if (!card || card.kind !== 'morph') return [];
  // Prefer the canonical parsed form when set — grammar.js cards can ship
  // a sparse human-friendly `answer` ("1st singular ('I am')") alongside
  // a `parsed:` ("present active indicative first person singular") that
  // populates every dimension the form actually carries.
  const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
  const includeAspect = options.includeAspect !== false;

  // Chapter-gated mood default. When the card is a finite verb (tense +
  // person/number, no case/gender) with no explicit mood in its parse,
  // AND the student's accessible pool already contains a non-indicative
  // mood (i.e. the curriculum has introduced something else to contrast
  // against), inject mood='indicative' so the Mood step appears and the
  // student commits explicitly rather than having indicative silently
  // implied. Before the contrast exists (early chapters), the Mood step
  // would be a no-info "pick indicative" — skipped.
  if (!dims.mood && (dims.tense || dims.voice) && (dims.person || dims.number)
      && !dims.case && !dims.gender) {
    const accessibleMoods = (accessiblePools && Array.isArray(accessiblePools.mood)) ? accessiblePools.mood : [];
    const hasContrast = accessibleMoods.some(m => m && m !== 'indicative');
    if (hasContrast) dims.mood = 'indicative';
  }

  // Determine the dimension order. Verbs lead with aspect → tense (Duff's
  // aspect-first pedagogy), then voice → mood → person → number, with a
  // case/number/gender tail for participles. Nominals skip the verb steps.
  const isVerb = !!(dims.tense || dims.voice || dims.person);
  const verbOrder = ['aspect', 'tense', 'voice', 'mood', 'person', 'case', 'number', 'gender'];
  const nominalOrder = ['case', 'number', 'gender', 'aspect', 'tense', 'voice', 'mood', 'person'];
  const order = (isVerb ? verbOrder : nominalOrder).filter(k => includeAspect || k !== 'aspect');

  const steps = [];
  const skippedCorrect = {}; // dim → correct value for steps we silently skipped
  const impliedDims = {};    // dim → correct value for steps skipped but kept in parse summary
  const maxChapter = Number.isFinite(options.maxChapter) ? options.maxChapter : Infinity;
  const dimToggles = (options.dimToggles && typeof options.dimToggles === 'object') ? options.dimToggles : null;
  const dimValueFilters = (options.dimValueFilters && typeof options.dimValueFilters === 'object') ? options.dimValueFilters : null;
  const multiGenderLemmas = options.multiGenderLemmas instanceof Set ? options.multiGenderLemmas : null;
  // Single-gender lemmas whose gender is non-obvious from the form
  // ending (1st-decl. masc. -ης/-ας nouns: προφήτης, μαθητής, …) —
  // override the single-gender auto-skip below so the gender step IS
  // asked. The form looks feminine; recalling the lemma is masculine is
  // the whole point of the drill for these.
  const mixedFormNouns = options.mixedFormNouns instanceof Set ? options.mixedFormNouns : null;
  for (const dimKey of order) {
    const correct = dims[dimKey];
    if (!correct) continue;
    // Imperative is structurally 2nd person in Koine — skip the person step
    // for imperative cards so the dimension count matches non-explicit
    // imperatives (e.g. "active imperative singular" with no "second person"
    // tag).
    if (dimKey === 'person' && dims.mood === 'imperative') continue;
    // Voice step: gate on chapter regardless of card voice. Duff
    // doesn't ask the student to choose a voice until ch 15, and the
    // deponent forms covered at ch 8/9 are taught as functionally
    // active (middle/passive in form, active in meaning) — so asking
    // "what voice is ἔρχομαι?" at ch 9 is a question Duff doesn't
    // expect a single right answer to. The voice gets silently filled
    // in (skippedCorrect) so the form lookup still resolves; at ch 15+
    // the step appears, with the deponent-accepts-active rule applied
    // when the step is built below.
    if (dimKey === 'voice' && maxChapter < VOICE_INTRODUCED_AT_CHAPTER) {
      skippedCorrect[dimKey] = correct;
      continue;
    }
    // Per-dim toggle: user-controlled opt-out. Off → step skipped, dim
    // doesn't contribute to stats, omitted from the parse summary; the
    // form lookup auto-fills the canonical correct value via
    // skippedCorrect below.
    if (dimToggles && dimKey !== 'aspect' && dimToggles[dimKey] === false) {
      skippedCorrect[dimKey] = correct;
      continue;
    }
    // Single-gender lemma auto-skip. Asking "what gender?" for a noun
    // like λόγος tests whether the student remembers the lemma's fixed
    // gender, not whether they're parsing the form — the form λόγου is
    // masculine because λόγος is, not because the genitive ending
    // distinguishes a gender. Multi-gender paradigms (articles,
    // adjectives, pronouns, participles) keep the step: there the form
    // genuinely commits to a gender. The implied gender is auto-filled
    // for form lookup AND surfaced in the final parse summary so the
    // canonical label still reads e.g. "genitive singular masculine".
    //
    // Exception: mixed-form nouns (1st-decl. masc. -ης/-ας like
    // προφήτης, μαθητής) keep the step. Their endings match the 1st-
    // decl. feminine pattern, so the form-shape misleads the student
    // into a feminine reading; the gender check is the whole point of
    // drilling these and the lemma's gender isn't "obvious from the
    // article" the way it is for λόγος.
    const isMixedFormNoun = !!(mixedFormNouns && card.lemma && mixedFormNouns.has(card.lemma));
    if (dimKey === 'gender' && multiGenderLemmas && card.lemma
        && !multiGenderLemmas.has(card.lemma)
        && !isMixedFormNoun) {
      skippedCorrect[dimKey] = correct;
      impliedDims[dimKey] = correct;
      continue;
    }
    const pool = accessiblePools ? accessiblePools[dimKey] : null;
    const choices = buildChoices(dimKey, correct, pool, dimValueFilters);
    const displayCorrect = applyDisplaySuffix(dimKey, correct);
    const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
    // Each dimension has exactly one correct value per card. For aspect on
    // present/future verbs the correct value is the composite
    // 'continuous/undefined' (since either reading is licensed by the form);
    // for imperfect/aorist/perfect/pluperfect it's a single specific aspect.
    // The aspect step carries a `context.tense` so the wrong-answer
    // comparator can spell out the mistake when picked and correct overlap
    // visually (e.g. picked "continuous" vs correct "continuous/undefined").
    const step = {
      key: dimKey,
      label: DIM_LABEL[dimKey] || dimKey,
      correct,
      acceptable: [correct],
      choices,
      displayCorrect,
      displayChoices
    };
    if (dimKey === 'aspect' && dims.tense) {
      step.context = { tense: dims.tense };
    }
    // Deponent voice handling. Duff treats deponent verbs (lemmas
    // ending in -μαι and εἰμί's future ἔσομαι family) as functionally
    // active even though the form is middle / middle-passive — so
    // when voice IS asked (ch 15+), both 'active' and the formal
    // middle voice should grade as correct. Genuine passives
    // (voice='passive') stay strict: passive isn't active in meaning.
    if (dimKey === 'voice' && (correct === 'middle' || correct === 'middle/passive')) {
      step.acceptable = [correct, 'active'];
    }
    if (dimKey === 'mood' && isSecondPluralPresentMoodAmbiguity(card.answer, dims)) {
      step.acceptable = ['indicative', 'imperative'];
    }
    steps.push(step);
  }
  // Attach the auto-filled-correct dim map as a property on the array
  // (rather than changing the return shape) so the caller can read it
  // alongside the steps for the form-lookup augmentation, while
  // callers that just want the step list keep working.
  steps.autoFilledDims = skippedCorrect;
  // `impliedDims` is a subset of skippedCorrect (currently just the
  // single-gender gender skip) that should still appear in the rendered
  // parse summary — the step wasn't asked, but the dim belongs to the
  // form's canonical label. Caller renders these inline with the
  // student-picked values.
  steps.impliedDims = impliedDims;
  return steps;
}

// ─── Per-lemma drill stats ──────────────────────────────────────────────
//
// Two structures per lemma:
//   - `attempts`:  sliding window of the last ATTEMPT_WINDOW raw attempts.
//                  Drives the header pct + the in-card "Last 20 attempts"
//                  rollup. Per-attempt, per-dimension correctness.
//   - `forms`:     { [cardId]: { seen, recent: [last 2 per-dim results] } }.
//                  The canonical per-form record: dots the testable-forms
//                  list, feeds the exclude-known-morphs filter, and — joined
//                  with each form's parsed dimension *values* — drives the
//                  per-value (per-mood / per-tense) proficiency breakdown.
//
// No cross-paradigm `overall` mirror and no disjoint bucket history are
// persisted: the breakdown is derived from `forms` at read time, so the
// aggregate views cost nothing extra in the save.

const ATTEMPT_WINDOW = 20;

export function ensureParadigmStepStats(store) {
  if (!store || typeof store !== 'object') return {};
  if (typeof store.byLemma !== 'object' || store.byLemma === null) store.byLemma = {};
  return store;
}

function ensureLemmaEntry(entry) {
  if (!Array.isArray(entry.attempts)) entry.attempts = [];
  if (!entry.forms || typeof entry.forms !== 'object') entry.forms = {};
  return entry;
}

const FORM_RECENT_CAP = 2;

// Record one attempt: a fully walked card with per-dimension correctness.
// stats: { byLemma: { lemma: { attempts: [{at, dims}],
//                              forms: { [cardId]: { seen, recent: [{dims}] } } } } }
// `formMeta` is optional: { cardId } stores the most recent FORM_RECENT_CAP
// per-dim results so the testable-forms list can dot each form by its last
// 1–2 attempts, the exclude-known-morphs filter can skip mastered forms, and
// the per-value breakdown can roll each form into its mood/tense/voice value.
export function recordParadigmAttempt(stats, lemma, dimResults, formMeta) {
  if (!lemma || !dimResults) return;
  ensureParadigmStepStats(stats);
  if (!stats.byLemma[lemma]) stats.byLemma[lemma] = {};
  const entry = ensureLemmaEntry(stats.byLemma[lemma]);

  if (formMeta && formMeta.cardId) {
    const prior = entry.forms[formMeta.cardId];
    const prevSeen = prior && Number.isFinite(prior.seen) ? prior.seen : 0;
    const priorRecent = Array.isArray(prior && prior.recent) ? prior.recent : [];
    const recent = priorRecent.concat([{ dims: { ...dimResults } }]).slice(-FORM_RECENT_CAP);
    entry.forms[formMeta.cardId] = { seen: prevSeen + 1, recent };
  }

  // Sliding window of raw attempts (drives the header pct + the in-card
  // "Last 20 attempts" rollup). Per-attempt, per-dimension correctness.
  entry.attempts.push({ at: Date.now(), dims: { ...dimResults } });
  while (entry.attempts.length > ATTEMPT_WINDOW) entry.attempts.shift();
}

// True if the given dim is currently enabled. `enabledDims` is the map
// returned by getEnabledParsingDims (main.js); a null/undefined value is
// treated as "all dims enabled" so callers that don't care about filters
// (e.g. import sanitization) still get the historical totals.
function isDimEnabled(enabledDims, dim) {
  if (!enabledDims) return true;
  return enabledDims[dim] !== false;
}

// Half-credit for an incomplete parse in the headline accuracy %. A parse
// where the student missed at least one (enabled) dimension contributes its
// correct dimensions at this weight, so completing a parse counts for more
// than a partially-right one. Only the weighted accuracy (`weightedCorrect`)
// uses this — the raw `correct`/`total` per-dimension counts are untouched,
// so the per-card "X/Y dimensions correct" readout stays literal.
const WRONG_PARSE_CREDIT = 0.5;

// Aggregate accuracy for a single lemma's recent attempts. When
// `enabledDims` is provided, per-dim values whose dim is currently
// toggled off are skipped — they don't contribute to the totals or to
// the per-dim chips, matching the user's current parsing scope.
//
// Returns raw `correct`/`total` (per-dimension hit counts) plus
// `weightedCorrect`, which discounts the correct dimensions of any
// not-fully-correct parse by WRONG_PARSE_CREDIT. Callers showing the
// headline accuracy % divide weightedCorrect / total; callers reporting a
// literal dimension tally use correct / total.
export function summarizeLemmaStats(stats, lemma, enabledDims) {
  const empty = { total: 0, correct: 0, weightedCorrect: 0, perDim: {}, attempts: 0 };
  if (!stats || !stats.byLemma || !stats.byLemma[lemma]) return empty;
  const attempts = stats.byLemma[lemma].attempts || [];
  let total = 0, correct = 0, weightedCorrect = 0;
  const perDim = {};
  for (const a of attempts) {
    if (!a || !a.dims) continue;
    let attemptTotal = 0, attemptCorrect = 0;
    for (const [dim, val] of Object.entries(a.dims)) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      if (!perDim[dim]) perDim[dim] = { seen: 0, correct: 0 };
      perDim[dim].seen += 1;
      if (val) perDim[dim].correct += 1;
      attemptTotal += 1;
      if (val) attemptCorrect += 1;
    }
    if (!attemptTotal) continue;
    total += attemptTotal;
    correct += attemptCorrect;
    weightedCorrect += attemptCorrect === attemptTotal
      ? attemptCorrect
      : attemptCorrect * WRONG_PARSE_CREDIT;
  }
  return { total, correct, weightedCorrect, perDim, attempts: attempts.length };
}

export function getAllLemmaStats(stats, enabledDims) {
  if (!stats || !stats.byLemma) return [];
  return Object.keys(stats.byLemma).map((lemma) => ({
    lemma,
    ...summarizeLemmaStats(stats, lemma, enabledDims)
  })).filter((s) => s.attempts > 0);
}

export function getParadigmStepDimensionLabel(dimKey) {
  return DIM_LABEL[dimKey] || dimKey;
}

// Re-evaluate a single recent attempt under the user's current dim toggles.
// Legacy attempts (saved before per-dim recording, only `allDims: bool`) keep
// their stored verdict since we no longer have the per-dim breakdown.
function evaluateRecentAttempt(attempt, enabledDims) {
  if (!attempt) return false;
  if (typeof attempt.allDims === 'boolean') return attempt.allDims;
  const dims = attempt.dims || {};
  for (const [dim, val] of Object.entries(dims)) {
    if (!isDimEnabled(enabledDims, dim)) continue;
    if (val !== 1) return false;
  }
  return true;
}

// Out-of-2 tally for one form, after filtering disabled dims. Returns
// { correct, total } where total is the number of recorded recent
// attempts (≤ FORM_RECENT_CAP) and correct is how many of those pass
// every currently-enabled dim.
export function countLemmaFormRecent(stats, lemma, cardId, enabledDims) {
  if (!cardId) return { correct: 0, total: 0 };
  const entry = stats?.byLemma?.[lemma];
  const form = entry?.forms && entry.forms[cardId];
  if (!form || !Array.isArray(form.recent) || !form.recent.length) {
    return { correct: 0, total: 0 };
  }
  let correct = 0;
  for (const a of form.recent) {
    if (evaluateRecentAttempt(a, enabledDims)) correct += 1;
  }
  return { correct, total: form.recent.length };
}

// Per-form recent-attempt status for the parsing-review "testable forms"
// list. Returns 'known' / 'right' / 'wrong' / 'uncertain' / 'unseen' based
// on the out-of-2 tally:
//   0/0 → unseen (grey)
//   1/1 → right (green)
//   2/2 → known (blue) — both recent attempts correct; the same threshold
//         isLemmaFormKnown uses for the exclude-known-morphs filter, so a
//         blue dot is exactly a form "skip confident" mode would drop.
//   1/2 → uncertain (yellow)
//   0/1, 0/2 → wrong (red)
// Parsing mode doesn't write to the directional progress store, so this is
// the canonical source for "have I attempted this form yet and how did it go."
export function getLemmaFormStatus(stats, lemma, cardId, enabledDims) {
  const { correct, total } = countLemmaFormRecent(stats, lemma, cardId, enabledDims);
  if (!total) return 'unseen';
  if (correct === total) return total >= FORM_RECENT_CAP ? 'known' : 'right';
  if (correct === 0) return 'wrong';
  return 'uncertain';
}

// Clears one form's per-form recent tally — drops it from the lemma's forms
// map so it reads as 'unseen' again and re-enters the deck when the
// exclude-known-morphs ("skip confident") filter is on. The lemma's rolling
// `attempts` window is intentionally left alone (same scoping as
// resetKnownMorphs, but for a single form). Returns true when something was
// actually cleared.
export function clearLemmaFormRecent(stats, lemma, cardId) {
  if (!stats || !stats.byLemma || !lemma || !cardId) return false;
  const entry = stats.byLemma[lemma];
  if (!entry || !entry.forms || !entry.forms[cardId]) return false;
  delete entry.forms[cardId];
  return true;
}

// Stricter "known" check for the exclude-known-morphs deck filter: the
// form has been correctly parsed in BOTH of its last two attempts. A
// single 1/1 is still green in the UI but isn't excluded here — the user
// has to demonstrate the form twice before parsing mode skips it.
export function isLemmaFormKnown(stats, lemma, cardId, enabledDims) {
  const { correct, total } = countLemmaFormRecent(stats, lemma, cardId, enabledDims);
  return total >= FORM_RECENT_CAP && correct >= FORM_RECENT_CAP;
}

export function getParadigmStepAttemptWindow() {
  return ATTEMPT_WINDOW;
}

// ─── Per-value proficiency breakdown ─────────────────────────────────────
//
// The headline pct and the old bucket bars aggregated across every form, so a
// student strong on present-indicative but weak on aorist-subjunctive read as
// uniformly fine. This breakdown joins each in-scope form's parsed *value*
// (which mood? which tense?) with its saved per-form recent tally, so weakness
// in a specific mood/tense/voice surfaces instead of averaging away.
//
// Derived entirely at read time from `forms` + the card's parse string — no
// new persisted data. `aspect` is intentionally omitted (it's a function of
// tense, already shown). Dimensions appear in this order; a dimension only
// renders when ≥2 of its values exist among the in-scope forms (otherwise
// there's nothing to compare).
const VALUE_BREAKDOWN_DIMS = ['tense', 'mood', 'voice', 'person', 'case', 'number', 'gender'];
const VALUE_ORDER = {
  tense:  ['present', 'future', 'imperfect', 'aorist', 'perfect', 'pluperfect'],
  mood:   ['indicative', 'subjunctive', 'imperative', 'infinitive', 'participle'],
  voice:  ['active', 'middle', 'passive', 'middle/passive'],
  person: ['first', 'second', 'third'],
  case:   ['nominative', 'accusative', 'genitive', 'dative', 'vocative'],
  number: ['singular', 'plural'],
  gender: ['masculine', 'feminine', 'neuter']
};
const VALUE_LABEL = {
  person: { first: '1st', second: '2nd', third: '3rd' },
  voice:  { 'middle/passive': 'mid/pass' }
};
function valueDisplayLabel(dim, val) {
  const override = VALUE_LABEL[dim] && VALUE_LABEL[dim][val];
  if (override) return override;
  return val.charAt(0).toUpperCase() + val.slice(1);
}
// Map a parsed dimension value to the atomic breakdown value(s). First/second
// aorist collapse into "aorist". Syncretic case/gender composites
// ("nominative/accusative", "masculine/feminine/neuter") split so the form
// counts toward each member — but a genuine atomic value (e.g. the
// "middle/passive" voice) is kept whole.
function breakdownValuesFor(dim, raw) {
  if (!raw) return [];
  let v = String(raw);
  if (dim === 'tense' && (v === 'first aorist' || v === 'second aorist')) v = 'aorist';
  if (VALUE_ORDER[dim].includes(v)) return [v];
  return v.split('/')
    .map((piece) => (dim === 'tense' && (piece === 'first aorist' || piece === 'second aorist') ? 'aorist' : piece))
    .filter((piece) => VALUE_ORDER[dim].includes(piece));
}

export function createValueBreakdownAcc() {
  const byDim = {};
  for (const dim of VALUE_BREAKDOWN_DIMS) byDim[dim] = {};
  // `totals` counts each form ONCE (not once per dimension) so it can drive a
  // paradigm-wide headline: recent attempts (≤2 per form) summed across every
  // in-scope form, plus seen/in-scope form coverage. This is what the per-
  // paradigm and "All paradigms" % now report — no longer the capped rolling
  // window, so the headline scales with the paradigm instead of the last 20
  // parses and stays consistent with the per-value bars.
  return { byDim, totals: { correct: 0, total: 0, seen: 0, scope: 0 } };
}

// Fold one lemma's in-scope cards into the accumulator. `cards` come from the
// same focused-paradigm pool the deck uses (chapter-gated), so coverage counts
// match what's actually drillable. Call once per lemma, reusing the acc, to
// build a cross-paradigm aggregate.
export function accumulateValueBreakdown(acc, stats, lemma, cards, enabledDims) {
  if (!acc || !Array.isArray(cards)) return acc;
  for (const card of cards) {
    if (!card || !card.id) continue;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
    const status = getLemmaFormStatus(stats, lemma, card.id, enabledDims);
    const { correct, total } = countLemmaFormRecent(stats, lemma, card.id, enabledDims);
    // Once-per-form paradigm-wide tally (recent attempts + coverage).
    acc.totals.scope += 1;
    if (status !== 'unseen') acc.totals.seen += 1;
    acc.totals.correct += correct;
    acc.totals.total += total;
    for (const dim of VALUE_BREAKDOWN_DIMS) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      for (const val of breakdownValuesFor(dim, dims[dim])) {
        const bag = acc.byDim[dim];
        if (!bag[val]) bag[val] = { forms: 0, seenForms: 0, correct: 0, total: 0 };
        const e = bag[val];
        e.forms += 1;
        if (status !== 'unseen') e.seenForms += 1;
        e.correct += correct;
        e.total += total;
      }
    }
  }
  return acc;
}

// Collapse the accumulator into render-ready groups (canonical value order),
// the single weakest seen value across every dimension — the "drill this next"
// pointer — and the paradigm-wide `totals` (headline % + form coverage). `pct`
// is null for a value with no recent attempts (rendered as an unseen track,
// surfacing coverage gaps).
export function finalizeValueBreakdown(acc, options = {}) {
  const minValues = Number.isFinite(options.minValues) ? options.minValues : 2;
  const groups = [];
  let weakest = null;
  const emptyTotals = { correct: 0, total: 0, seen: 0, scope: 0, pct: null };
  if (!acc || !acc.byDim) return { groups, weakest, totals: emptyTotals };
  for (const dim of VALUE_BREAKDOWN_DIMS) {
    const bag = acc.byDim[dim];
    const present = VALUE_ORDER[dim].filter((v) => bag[v]);
    if (present.length < minValues) continue;
    const rows = present.map((v) => {
      const e = bag[v];
      const pct = e.total ? Math.round(100 * e.correct / e.total) : null;
      if (pct != null && e.seenForms > 0 && (!weakest || pct < weakest.pct)) {
        weakest = { dim, value: v, label: valueDisplayLabel(dim, v), pct };
      }
      return {
        value: v,
        label: valueDisplayLabel(dim, v),
        pct,
        forms: e.forms,
        seenForms: e.seenForms
      };
    });
    groups.push({ dim, label: DIM_LABEL[dim] || dim, rows });
  }
  const t = acc.totals || emptyTotals;
  const totals = {
    correct: t.correct,
    total: t.total,
    seen: t.seen,
    scope: t.scope,
    pct: t.total ? Math.round(100 * t.correct / t.total) : null
  };
  return { groups, weakest, totals };
}

// Convenience: full breakdown for a single lemma in one call.
export function summarizeLemmaValueBreakdown(stats, lemma, cards, enabledDims, options) {
  const acc = createValueBreakdownAcc();
  accumulateValueBreakdown(acc, stats, lemma, cards, enabledDims);
  return finalizeValueBreakdown(acc, options);
}
